package co.mycompany.restaurante.cliente.presentacion.mediodepago;
import static co.mycompany.restaurante.cliente.infra.Messages.successMessage;
import co.mycompany.restaurante.cliente.presentacion.GUIPagPagos;
import javax.swing.JOptionPane;
/**
 *
 * @author Kevith Felipe Bastidas
 */
public class GUIPagBancoPSE extends javax.swing.JInternalFrame{

    /**
     * Instancia de la vistaMenuPlato
     */
    private final GUIPagPagos vistaPagos;
    /**
     * Creates new form GUISeleccionBancoPSE
     * @param vistaPagos
     */
    public GUIPagBancoPSE(GUIPagPagos vistaPagos) {
        initComponents();
        this.vistaPagos = vistaPagos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        cmbBxBanco = new javax.swing.JComboBox<>();
        lbControlEspacioTitulo = new javax.swing.JLabel();
        lbSeleccionBanco = new javax.swing.JLabel();
        lbControlCentroIzq = new javax.swing.JLabel();
        lbControlCentroDer = new javax.swing.JLabel();
        btnCancelarPedido = new javax.swing.JButton();
        btnConfirmarPedido = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pago con PSE");

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cmbBxBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANCO AGRARIO", "NEQUI", "BANCO AV VILLAS", "BANCO CAJA SOCIAL", "SCOTIABANK COLPATRIA", "BANCO COOPERATIVO COOPCENTRAL", "BANCO DAVIVIENDA", "BANCO DE BOGOTÁ", "BANCO DE OCCIDENTE", "BANCO FALABELLA", "BANCO GNB SUDAMERIS", "BANCO PICHINCHA S.A", "BANCO POPULAR", "BANCOLOMBIA", "BANCOOMEVA S.A", "BANCO BBVA COLOMBIA S.A", "CITIBANK", "BANCO ITAÚ", "CONFIAR COOPERATIVA FINANCIERA", "DAVIPLATA", "BANCO DE LAS MICROFINANZAS BANCAMIA", "COLTEFINANCIERA", "CFA COOPERATIVA FINANCIERA", "BANCO CREDIFINANCIERA", "RAPPIPAY", "COTRAFA", "BANCO SANTANDER COLOMBIA", "BANCO SERFINANZA", "GIROS Y FINANZAS" }));

        lbControlEspacioTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbControlEspacioTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo-pse.png"))); // NOI18N

        lbSeleccionBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSeleccionBanco.setText("Seleccione su banco:");

        btnCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/regreso.png"))); // NOI18N
        btnCancelarPedido.setText("Cancelar pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        btnConfirmarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirmar.png"))); // NOI18N
        btnConfirmarPedido.setText("Confirmar pedido");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbControlEspacioTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSeleccionBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lbControlCentroIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBxBanco, 0, 325, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbControlCentroDer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmarPedido)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbControlEspacioTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSeleccionBanco)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbControlCentroIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbControlCentroDer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbBxBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
        successMessage("Su pedido ha sido registrado por el restaurante","Pedido registrado");
        this.vistaPagos.getVistaPrincipal().agregarComponente(this.vistaPagos.getVistaMenuPlato());
        this.vistaPagos.getVistaMenuPlato().generarPedido("PSE");
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        this.vistaPagos.getVistaPrincipal().agregarComponente(this.vistaPagos.getVistaMenuPlato());
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JComboBox<String> cmbBxBanco;
    private javax.swing.JLabel lbControlCentroDer;
    private javax.swing.JLabel lbControlCentroIzq;
    private javax.swing.JLabel lbControlEspacioTitulo;
    private javax.swing.JLabel lbSeleccionBanco;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
