/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.mycompany.restaurante.cliente.sistemadepago;

import co.mycompany.restaurante.cliente.presentacion.GUIPagPagos;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevith Felipe Bastidas
 */
public class GUIPagTarjetaCredito extends javax.swing.JInternalFrame {

    /**
     * Instancia de la vistaMenuPlato
     */
    private final GUIPagPagos vistaPagos;
    /**
     * Creates new form GUIDatosTarjeta
     * @param vistaPagos
     */
    public GUIPagTarjetaCredito(GUIPagPagos vistaPagos) {
        initComponents();
        this.vistaPagos = vistaPagos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lbControlEspacioTitulo = new javax.swing.JLabel();
        lbNumTarjeta = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        lbNombreApellido = new javax.swing.JLabel();
        lbFechaExp = new javax.swing.JLabel();
        lbCodigoSeguridad = new javax.swing.JLabel();
        lbTipoID = new javax.swing.JLabel();
        txtNombreApellido = new javax.swing.JTextField();
        txtFechaExp = new javax.swing.JTextField();
        txtCodigoSeguridad = new javax.swing.JTextField();
        cmbBxTipoID = new javax.swing.JComboBox<>();
        lbNumDocumentoID = new javax.swing.JLabel();
        txtNumDocumentoID = new javax.swing.JTextField();
        lbControlCentroDer = new javax.swing.JLabel();
        btnCancelarPedido = new javax.swing.JButton();
        btnConfirmarPedido = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pago con tarjeta de crédito");
        setFrameIcon(null);

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbControlEspacioTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbControlEspacioTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pago-con-tarjetas-de-credito.png"))); // NOI18N

        lbNumTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumTarjeta.setText("* Número de tarjeta:");

        txtNumTarjeta.setText("4000-0012-3456-7899");

        lbNombreApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreApellido.setText("* Nombre y apellido:");

        lbFechaExp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFechaExp.setText("* Fecha de expiración:");

        lbCodigoSeguridad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigoSeguridad.setText("* Código de seguridad:");

        lbTipoID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTipoID.setText("* Tipo Documento:");

        txtNombreApellido.setText("Customer");

        txtFechaExp.setText("01/25");

        txtCodigoSeguridad.setText("224");

        cmbBxTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "C.E", "NIT" }));

        lbNumDocumentoID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumDocumentoID.setText("* Número Documento:");

        txtNumDocumentoID.setText("1061928375");

        btnCancelarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/regreso.png"))); // NOI18N
        btnCancelarPedido.setText("Cancelar pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        btnConfirmarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/confirmar.png"))); // NOI18N
        btnConfirmarPedido.setText("Confirmar pedido");
        btnConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbControlEspacioTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbNumDocumentoID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTipoID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbCodigoSeguridad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lbFechaExp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNombreApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNumTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreApellido)
                            .addComponent(txtFechaExp)
                            .addComponent(txtCodigoSeguridad)
                            .addComponent(cmbBxTipoID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumDocumentoID)
                            .addComponent(txtNumTarjeta))
                        .addGap(18, 18, 18)
                        .addComponent(lbControlCentroDer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbControlEspacioTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumTarjeta)
                    .addComponent(txtNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbControlCentroDer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreApellido)
                    .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipoID)
                    .addComponent(cmbBxTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumDocumentoID)
                    .addComponent(txtNumDocumentoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFechaExp)
                    .addComponent(txtFechaExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoSeguridad)
                    .addComponent(txtCodigoSeguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirmarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidoActionPerformed
        if(txtNumTarjeta.getText().isBlank() || 
           txtNombreApellido.getText().isBlank() || 
           txtNumDocumentoID.getText().isBlank() ||
           txtFechaExp.getText().isBlank() ||
           txtCodigoSeguridad.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Debe completar todos los campos",
                    "Campos incompletos", JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null, "Su pedido ha sido registrado por el restaurante", 
                "Pedido registrado", JOptionPane.OK_OPTION);
            this.vistaPagos.getVistaPrincipal().agregarComponente(this.vistaPagos.getVistaMenuPlato());
            this.vistaPagos.getVistaMenuPlato().generarPedido("TarjetaCredito");
        }
        
    }//GEN-LAST:event_btnConfirmarPedidoActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // TODO add your handling code here:
        this.vistaPagos.getVistaPrincipal().agregarComponente(this.vistaPagos.getVistaMenuPlato());
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnConfirmarPedido;
    private javax.swing.JComboBox<String> cmbBxTipoID;
    private javax.swing.JLabel lbCodigoSeguridad;
    private javax.swing.JLabel lbControlCentroDer;
    private javax.swing.JLabel lbControlEspacioTitulo;
    private javax.swing.JLabel lbFechaExp;
    private javax.swing.JLabel lbNombreApellido;
    private javax.swing.JLabel lbNumDocumentoID;
    private javax.swing.JLabel lbNumTarjeta;
    private javax.swing.JLabel lbTipoID;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField txtCodigoSeguridad;
    private javax.swing.JTextField txtFechaExp;
    private javax.swing.JTextField txtNombreApellido;
    private javax.swing.JTextField txtNumDocumentoID;
    private javax.swing.JTextField txtNumTarjeta;
    // End of variables declaration//GEN-END:variables
}
