/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.guisprojectrestaurant;

/**
 *
 * @author Whalen Stiven Caicedo  <whastica@unicauca.edu.co>
 */
public class guiPedidoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form guiPedidoUsuario
     */
    public guiPedidoUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipal = new javax.swing.JPanel();
        JpSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JpOpciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JpPanelBotones = new javax.swing.JPanel();
        BtnAñadirPedido = new javax.swing.JButton();
        BtnAyuda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JpCentral = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPPrincipal.setLayout(new java.awt.BorderLayout());

        JpSuperior.setBackground(new java.awt.Color(138, 0, 58));
        JpSuperior.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(159, 0, 70));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rest.jpg"))); // NOI18N
        JpSuperior.add(jLabel1, java.awt.BorderLayout.CENTER);

        JpOpciones.setLayout(new java.awt.BorderLayout());
        JpOpciones.add(jLabel2, java.awt.BorderLayout.PAGE_START);
        JpOpciones.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        JpPanelBotones.setBackground(new java.awt.Color(138, 0, 58));

        BtnAñadirPedido.setBackground(new java.awt.Color(138, 0, 58));
        BtnAñadirPedido.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        BtnAñadirPedido.setText("Añadir pedido");

        BtnAyuda.setBackground(new java.awt.Color(138, 0, 58));
        BtnAyuda.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        BtnAyuda.setText("Ayuda en linea");

        jLabel3.setText("         ");

        javax.swing.GroupLayout JpPanelBotonesLayout = new javax.swing.GroupLayout(JpPanelBotones);
        JpPanelBotones.setLayout(JpPanelBotonesLayout);
        JpPanelBotonesLayout.setHorizontalGroup(
            JpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAñadirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        JpPanelBotonesLayout.setVerticalGroup(
            JpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAñadirPedido)
                    .addComponent(BtnAyuda)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38))
        );

        JpOpciones.add(JpPanelBotones, java.awt.BorderLayout.CENTER);

        JpSuperior.add(JpOpciones, java.awt.BorderLayout.EAST);

        jLabel9.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        jLabel9.setText("  Pedidos de usuario     ");
        JpSuperior.add(jLabel9, java.awt.BorderLayout.WEST);

        jPPrincipal.add(JpSuperior, java.awt.BorderLayout.PAGE_START);

        JpCentral.setBackground(new java.awt.Color(204, 204, 204));
        JpCentral.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("         ");
        JpCentral.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel6.setText("             ");
        JpCentral.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jLabel7.setText("         ");
        JpCentral.add(jLabel7, java.awt.BorderLayout.PAGE_END);

        jLabel8.setText("           ");
        JpCentral.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Pedido", "Restaurante", "Estado", "Title 5", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JpCentral.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPPrincipal.add(JpCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiPedidoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiPedidoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiPedidoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiPedidoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiPedidoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAyuda;
    private javax.swing.JButton BtnAñadirPedido;
    private javax.swing.JPanel JpCentral;
    private javax.swing.JPanel JpOpciones;
    private javax.swing.JPanel JpPanelBotones;
    private javax.swing.JPanel JpSuperior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}

